### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Policarpo7** [sandrocods/Zefoy-Automation#10]
is_from_webapp=1&sender_device=pc&web_id=7159758318801847813
Traceback (most recent call last):
  File "/home/policarpo/Zefoy-Automation/main.py", line 242, in <module>
    main()
  File "/home/policarpo/Zefoy-Automation/main.py", line 25, in main
    inject.get_session_captcha()
  File "/home/policarpo/Zefoy-Automation/src/process.py", line 60, in get_session_captcha
    url=self.API_ZEFOY + soup.find('img', {'alt': 'CAPTCHA code'}).get('src'),
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by sandrocods** [comment]
dont use vpn
