### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by Elliottophellia** [sandrocods/Zefoy-Automation#3]
```
Traceback (most recent call last):
  File "/home/ophellia/tiktok/main.py", line 180, in <module>
    main()
  File "/home/ophellia/tiktok/main.py", line 32, in main
    inject.get_session_captcha()
  File "/home/ophellia/tiktok/src/process.py", line 59, in get_session_captcha
    url=self.API_ZEFOY + soup.find('img', {'alt': 'CAPTCHA code'}).get('src'),
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Elliottophellia** [comment]
lol i though something was wrong but actually the web is down
